import test from 'node:test';import assert from 'node:assert/strict';
import {createChatObserver,cleanChatRecord,wrapChatOptions} from './chat-observer.mjs';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {EventEmitter} from 'node:events';
import {installChatLogSink} from './chat-log-sink.mjs';
const A='gpt-5-6-thinking',B='gpt-5-5-mini';
const make=(mode='request')=>createChatObserver({request:{model:A,conversation_id:'conv-a'},turnTraceId:'trace-a'},()=>{},mode);
const telemetry=(model)=>({type:'server-ste-metadata',conversationId:'conv-a',serverSteMetadata:{conversation_id:'conv-a',metadata:{model_slug:model}}});
const message=(model,role='assistant',resolved)=>({type:'message',conversationId:'conv-a',message:{id:'msg-'+role,author:{role},metadata:{model_slug:model,resolved_model_slug:resolved},content:{parts:['PRIVATE_REPLY']}}});
test('A equal sources do not mark a difference',()=>{const o=make();o.update(telemetry(A));o.update(message(A,'assistant',A));assert.equal(o.snapshot().metadataDifference,false);});
test('B telemetry mismatch is not explicit reroute',()=>{const o=make();o.update(telemetry(B));o.update(message(A));assert.equal(o.snapshot().metadataDifference,true);assert.equal(o.snapshot().explicitReroute,false);});
test('C explicit event is required for explicit reroute',()=>{const o=make();o.update({type:'model/rerouted',fromModel:A,toModel:B});assert.equal(o.snapshot().explicitReroute,true);assert.equal(o.snapshot().metadataDifference,true);});
test('D missing telemetry remains null',()=>{const o=make();o.update(message(A));assert.equal(o.snapshot().serverTelemetryModel,null);assert.equal(o.snapshot().explicitReroute,false);});
test('E missing assistant model never falls back',()=>{const o=make();o.update(telemetry(A));o.update(message(undefined));assert.equal(o.snapshot().assistantMessageModel,null);});
test('F resume and fresh streams cannot share records',()=>{const old=make('resume'),fresh=make();old.update(telemetry(B));fresh.update(message(A));assert.notEqual(old.snapshot().observationId,fresh.snapshot().observationId);assert.equal(old.snapshot().requestModel,null);assert.equal(fresh.snapshot().serverTelemetryModel,null);fresh.update({...telemetry(B),conversationId:'other'});assert.equal(fresh.snapshot().serverTelemetryModel,null);});
test('G only whitelist persists even when unknown fields carry secrets',()=>{const o=make(),event=telemetry(B);Object.assign(event.serverSteMetadata.metadata,{prompt:'SECRET',Authorization:'SECRET',token:'SECRET',cookie:'SECRET',account_id:'SECRET',ip:'192.0.2.1',cluster_region:'region-a',tool_invoked:'none',did_auto_switch_to_reasoning:false});o.update(event);o.update(message(A));const cleaned=cleanChatRecord({...o.snapshot(),fullServerMetadata:event,body:'SECRET'});assert.doesNotMatch(JSON.stringify(cleaned),/SECRET|PRIVATE_REPLY|192\.0\.2\.1|Authorization|fullServerMetadata/);assert.equal(cleaned.clusterRegion,'region-a');assert.equal(cleaned.didAutoSwitchToReasoning,false);assert.equal(cleaned.toolInvoked,'none');});
test('resolved source role retained independently',()=>{const o=make();o.update(message(A,'user',B));o.update(message(A));assert.equal(o.snapshot().resolvedModelRole,'user');assert.equal(o.snapshot().resolvedModelSlug,B);assert.equal(o.snapshot().metadataDifference,true);});
test('wrapper preserves arguments, return values and callback exceptions',()=>{let original;const opts={request:{model:A},onUpdate(event){original=event;return 123;},onRequestStart(){return 456;}};const wrapped=wrapChatOptions(opts,()=>{throw Error('sink');},'request');const event=message(A);assert.equal(wrapped.onUpdate(event),123);assert.equal(original,event);assert.equal(wrapped.onRequestStart(),456);assert.equal(wrapped.request,opts.request);});
test('Work reroute is not assigned to Chat',()=>{const o=make();o.update({method:'model/rerouted',params:{threadId:'work-thread',fromModel:A,toModel:B}});assert.equal(o.snapshot().explicitReroute,false);});
test('removed resolved field does not leave a stale difference',()=>{const o=make();o.update(message(A,'assistant',B));assert.equal(o.snapshot().metadataDifference,true);o.update(message(A));assert.equal(o.snapshot().resolvedModelSlug,null);assert.equal(o.snapshot().metadataDifference,false);});
test('conflicting and nested conversation IDs cannot cross streams',()=>{const o=make();const e=telemetry(B);e.serverSteMetadata.conversation_id='other';o.update(e);o.update({method:'model/rerouted',params:{conversationId:'other',fromModel:A,toModel:B}});assert.equal(o.snapshot().serverTelemetryModel,null);assert.equal(o.snapshot().explicitReroute,false);});
test('callback receiver and thrown exception are preserved',()=>{const receiver={tag:1},error=Error('original');let seen;const w=wrapChatOptions({request:{},onUpdate(){seen=this;throw error;}},()=>{},'request');assert.throws(()=>w.onUpdate.call(receiver,message(A)),e=>e===error);assert.equal(seen,receiver);});
test('native log sink revalidates fields and updates one file per observation',()=>{
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'chat-observer-test-')),app=new EventEmitter(),contents=new EventEmitter();
  installChatLogSink(app,fs,path,dir,cleanChatRecord);app.emit('web-contents-created',{},contents);
  const o=make();let record=o.snapshot();const send=r=>contents.emit('console-message',{}, {message:'GPTWIDGET_CHAT_METADATA:'+JSON.stringify({...r,Authorization:'SECRET_AUTH',prompt:'SECRET_PROMPT'})});
  send(record);o.update(telemetry(B));send(o.snapshot());
  const files=fs.readdirSync(dir);assert.equal(files.length,1);const text=fs.readFileSync(path.join(dir,files[0]),'utf8');assert.doesNotMatch(text,/SECRET/);assert.equal(JSON.parse(text).metadataDifference,true);
  contents.emit('console-message',{}, {message:'PRIVATE arbitrary console text'});assert.equal(fs.readdirSync(dir).length,1);
  // Remove only the exact generated fixture files, without recursive deletion.
  for(const file of files)fs.unlinkSync(path.join(dir,file));fs.rmdirSync(dir);
});
